#ifndef SECURITY_CONFIGS_H
#define SECURITY_CONFIGS_H

#include "security_defines.h"

#define SECURITY_LEVEL              (MIN_SECURITY_LEVEL)


#define PBKDF2_HMAC_SHA1            (ENABLED) 
#define PBKDF2_HMAC_SHA256          (ENABLED) 
#define PBKDF2_HMAC_SHA512          (ENABLED) 


#define SECURED_SHA1
#define SECURED_SHA256
#define SECURED_SHA512

#define SECURED_HMAC_SHA1
#define SECURED_HMAC_SHA256
#define SECURED_HMAC_SHA512

#define SECURED_PBKDF2_HMAC_SHA1
#define SECURED_PBKDF2_HMAC_SHA256
#define SECURED_PBKDF2_HMAC_SHA512

#define SECURED_KBKDF_HMAC_SHA1
#define SECURED_KBKDF_HMAC_SHA256
#define SECURED_KBKDF_HMAC_SHA512


//#define SHA1_MIN_SIZE
//#define SHA256_MIN_SIZE
//#define SHA256_MIN_SIZE
//
//#define HMAC_SHA1_MIN_SIZE
//#define HMAC_SHA256_MIN_SIZE
//#define HMAC_SHA256_MIN_SIZE
//
//#define PBKDF2_HMAC_SHA1_MIN_SIZE
//#define PBKDF2_HMAC_SHA256_MIN_SIZE
//#define PBKDF2_HMAC_SHA256_MIN_SIZE
//
//#define KBKDF_HMAC_SHA1_MIN_SIZE
//#define KBKDF_HMAC_SHA256_MIN_SIZE
//#define KBKDF_HMAC_SHA256_MIN_SIZE


#endif /* SECURITY_CONFIGS_H */